### ISSUE TITLE
Create clrs2016 branch

### ISSUE THREAD

**Issue by rajesh06** [PirateGrunt/raw#9]
Brian - Do we need / want a new branch for CLRS

**Comment by PirateGrunt** [comment]
Raj,
Sorry for the delayed reply. I actually created a new, blank repository called "raw_clrs", which may be found here: https://github.com/PirateGrunt/raw_clrs. You're listed as a collaborator for this repo.
The branching for "raw" had gotten a bit nuts between workshops, a package and book-length notes.
Regards,Brian

```
  From: Rajesh Sahasrabuddhe <notifications@github.com>
```

 To: PirateGrunt/raw raw@noreply.github.com 
 Sent: Wednesday, May 4, 2016 9:33 AM
 Subject: [PirateGrunt/raw] Create clrs2016 branch (#9)

Brian - Do we need / want a new branch for CLRS—
